// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:pokedex_3d/data/models/evolution_chain_model.dart';
import 'package:pokedex_3d/data/services/local/hive_models/evolution_detail_hive_model.dart';
import 'package:pokedex_3d/data/services/local/hive_models/pokemon_3d_hive_model.dart';
import 'package:pokedex_3d/data/services/local/hive_models/pokemon_detail_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EvolutionDetailHiveAdapter());
    registerAdapter(Pokemon3dHiveAdapter());
    registerAdapter(PokemonChainNodeAdapter());
    registerAdapter(PokemonDetailHiveAdapter());
    registerAdapter(PokemonFormHiveAdapter());
    registerAdapter(PokemonSpeciesHiveAdapter());
    registerAdapter(StatHiveAdapter());
    registerAdapter(TriggerDetailHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EvolutionDetailHiveAdapter());
    registerAdapter(Pokemon3dHiveAdapter());
    registerAdapter(PokemonChainNodeAdapter());
    registerAdapter(PokemonDetailHiveAdapter());
    registerAdapter(PokemonFormHiveAdapter());
    registerAdapter(PokemonSpeciesHiveAdapter());
    registerAdapter(StatHiveAdapter());
    registerAdapter(TriggerDetailHiveAdapter());
  }
}
